insert into common_noun_baker_translations (lemma, english_translation) values ('αἰών','eternity');
insert into common_noun_baker_translations (lemma, english_translation) values ('βαλλάντιον','purse');
insert into common_noun_baker_translations (lemma, english_translation) values ('βασιλεία','kingdom');
insert into common_noun_baker_translations (lemma, english_translation) values ('βασιλεύς','king');
insert into common_noun_baker_translations (lemma, english_translation) values ('βιβλίον','scroll, book');
insert into common_noun_baker_translations (lemma, english_translation) values ('βλασφημία','blasphemy');
insert into common_noun_baker_translations (lemma, english_translation) values ('βοῦς','ox');
insert into common_noun_baker_translations (lemma, english_translation) values ('βρέφος','babies');
insert into common_noun_baker_translations (lemma, english_translation) values ('γάμος','wedding');
insert into common_noun_baker_translations (lemma, english_translation) values ('γενεά','generation');
insert into common_noun_baker_translations (lemma, english_translation) values ('γεωργός','farmer, tenant');
insert into common_noun_baker_translations (lemma, english_translation) values ('γραμματεύς','teacher, expert in the law, scholar, scribe');
insert into common_noun_baker_translations (lemma, english_translation) values ('γραφή','Scripture');
insert into common_noun_baker_translations (lemma, english_translation) values ('γυνή','wife, woman');
insert into common_noun_baker_translations (lemma, english_translation) values ('δάκτυλος','finger');
insert into common_noun_baker_translations (lemma, english_translation) values ('δένδρον','tree	');
insert into common_noun_baker_translations (lemma, english_translation) values ('δίκτυον','fishing net');
insert into common_noun_baker_translations (lemma, english_translation) values ('δαιμόνιον','demon');
insert into common_noun_baker_translations (lemma, english_translation) values ('δηνάριον','denarius (about a day''s wages)');
insert into common_noun_baker_translations (lemma, english_translation) values ('διάκονος','servant, minister, deacon');
insert into common_noun_baker_translations (lemma, english_translation) values ('διαλογισμός','thought, argument');
insert into common_noun_baker_translations (lemma, english_translation) values ('δοῦλος','servant, slave');
insert into common_noun_baker_translations (lemma, english_translation) values ('δραχμή','silver coin, drachma');
insert into common_noun_baker_translations (lemma, english_translation) values ('δύναμις','power, ability, miracle');
insert into common_noun_baker_translations (lemma, english_translation) values ('δῶρον','gift');
insert into common_noun_baker_translations (lemma, english_translation) values ('ζεῦγος','yoke, pair');
insert into common_noun_baker_translations (lemma, english_translation) values ('ζώνη','belt');
insert into common_noun_baker_translations (lemma, english_translation) values ('θεός','God');
insert into common_noun_baker_translations (lemma, english_translation) values ('θησαυρός','treasure');
insert into common_noun_baker_translations (lemma, english_translation) values ('θρίξ','hair');
insert into common_noun_baker_translations (lemma, english_translation) values ('θρόνος','throne');
insert into common_noun_baker_translations (lemma, english_translation) values ('θυγάτηρ','daughter');
insert into common_noun_baker_translations (lemma, english_translation) values ('καιρός','time, right time');
insert into common_noun_baker_translations (lemma, english_translation) values ('καρδία','heart');
insert into common_noun_baker_translations (lemma, english_translation) values ('καρπός','fruit, crop, harvest');
insert into common_noun_baker_translations (lemma, english_translation) values ('κεφαλή','head');
insert into common_noun_baker_translations (lemma, english_translation) values ('κλέπτης','thief');
insert into common_noun_baker_translations (lemma, english_translation) values ('κλῆμα','branch');
insert into common_noun_baker_translations (lemma, english_translation) values ('κλῆρος','lots (casting of lots), inheritance');
insert into common_noun_baker_translations (lemma, english_translation) values ('κοιλία','womb, stomach, source of feelings and emotions');
insert into common_noun_baker_translations (lemma, english_translation) values ('κριτής','judge');
insert into common_noun_baker_translations (lemma, english_translation) values ('κόπος','labour, work, trouble, difficulty');
insert into common_noun_baker_translations (lemma, english_translation) values ('κύριος','Lord, lord, master');
insert into common_noun_baker_translations (lemma, english_translation) values ('κώμη','village');
insert into common_noun_baker_translations (lemma, english_translation) values ('λίθος','stone');
insert into common_noun_baker_translations (lemma, english_translation) values ('λίτρα','unit of measure around 300 grams');
insert into common_noun_baker_translations (lemma, english_translation) values ('λιμός','famine');
insert into common_noun_baker_translations (lemma, english_translation) values ('λόγος','word');
insert into common_noun_baker_translations (lemma, english_translation) values ('λύχνος','lamp');
insert into common_noun_baker_translations (lemma, english_translation) values ('λῃστής','robber');
insert into common_noun_baker_translations (lemma, english_translation) values ('μέριμνα','worry, concern, desire');
insert into common_noun_baker_translations (lemma, english_translation) values ('μέρος','part');
insert into common_noun_baker_translations (lemma, english_translation) values ('μήτηρ','mother');
insert into common_noun_baker_translations (lemma, english_translation) values ('μαθητής','disciple');
insert into common_noun_baker_translations (lemma, english_translation) values ('μαργαρίτης','pearls');
insert into common_noun_baker_translations (lemma, english_translation) values ('μνημεῖον','tomb, grave');
insert into common_noun_baker_translations (lemma, english_translation) values ('μνᾶ','mina (about 100 days'' wages)');
insert into common_noun_baker_translations (lemma, english_translation) values ('μύρον','myrrh');
insert into common_noun_baker_translations (lemma, english_translation) values ('νόσος','disease');
insert into common_noun_baker_translations (lemma, english_translation) values ('νύξ','night');
insert into common_noun_baker_translations (lemma, english_translation) values ('οἰκία','house');
insert into common_noun_baker_translations (lemma, english_translation) values ('οὐρανός','heaven, sky');
insert into common_noun_baker_translations (lemma, english_translation) values ('οὖς','ear');
insert into common_noun_baker_translations (lemma, english_translation) values ('παιδίον','child');
insert into common_noun_baker_translations (lemma, english_translation) values ('παραβολή','parable');
insert into common_noun_baker_translations (lemma, english_translation) values ('παρθένος','virgin');
insert into common_noun_baker_translations (lemma, english_translation) values ('πατήρ','father');
insert into common_noun_baker_translations (lemma, english_translation) values ('παῖς','child');
insert into common_noun_baker_translations (lemma, english_translation) values ('περιστερά','dove');
insert into common_noun_baker_translations (lemma, english_translation) values ('πλήρωμα','fullness');
insert into common_noun_baker_translations (lemma, english_translation) values ('πλοιάριον','small boat');
insert into common_noun_baker_translations (lemma, english_translation) values ('πλοῖον','boat');
insert into common_noun_baker_translations (lemma, english_translation) values ('πνεῦμα','wind, breath, spirit');
insert into common_noun_baker_translations (lemma, english_translation) values ('ποιμήν','shepherd, pastor');
insert into common_noun_baker_translations (lemma, english_translation) values ('ποταμός','river');
insert into common_noun_baker_translations (lemma, english_translation) values ('πούς','foot');
insert into common_noun_baker_translations (lemma, english_translation) values ('προφήτης','prophet');
insert into common_noun_baker_translations (lemma, english_translation) values ('πρωτοκαθεδρία','most important seat, seat of honour');
insert into common_noun_baker_translations (lemma, english_translation) values ('πρωτοκλισία','place of honor');
insert into common_noun_baker_translations (lemma, english_translation) values ('πρόβατον','sheep');
insert into common_noun_baker_translations (lemma, english_translation) values ('πρόσωπον','face');
insert into common_noun_baker_translations (lemma, english_translation) values ('πόλεμος','war');
insert into common_noun_baker_translations (lemma, english_translation) values ('πόλις','city');
insert into common_noun_baker_translations (lemma, english_translation) values ('πύλη','city gate');
insert into common_noun_baker_translations (lemma, english_translation) values ('σεισμός','earthquakes, storm');
insert into common_noun_baker_translations (lemma, english_translation) values ('σημεῖον','sign');
insert into common_noun_baker_translations (lemma, english_translation) values ('σκεῦος','possession, object, thing, jar, vessel');
insert into common_noun_baker_translations (lemma, english_translation) values ('στάχυς','head of grain');
insert into common_noun_baker_translations (lemma, english_translation) values ('σταφυλή','grapes');
insert into common_noun_baker_translations (lemma, english_translation) values ('στῆθος','chest, breast');
insert into common_noun_baker_translations (lemma, english_translation) values ('συνέδριον','council');
insert into common_noun_baker_translations (lemma, english_translation) values ('συναγωγή','synagogue');
insert into common_noun_baker_translations (lemma, english_translation) values ('σῶμα','body');
insert into common_noun_baker_translations (lemma, english_translation) values ('τάλαντον','talent (weight and monetary unit: around 20 years'' wages)');
insert into common_noun_baker_translations (lemma, english_translation) values ('τάφος','tomb, grave');
insert into common_noun_baker_translations (lemma, english_translation) values ('τέκνον','child');
insert into common_noun_baker_translations (lemma, english_translation) values ('τέλος','end');
insert into common_noun_baker_translations (lemma, english_translation) values ('τελώνης','tax collector');
insert into common_noun_baker_translations (lemma, english_translation) values ('τράπεζα','table');
insert into common_noun_baker_translations (lemma, english_translation) values ('τροφή','food');
insert into common_noun_baker_translations (lemma, english_translation) values ('τόπος','place');
insert into common_noun_baker_translations (lemma, english_translation) values ('υἱός','son');
insert into common_noun_baker_translations (lemma, english_translation) values ('φραγμός','barrier, wall');
insert into common_noun_baker_translations (lemma, english_translation) values ('φυλακή','prison');
insert into common_noun_baker_translations (lemma, english_translation) values ('φωνή','voice or sound');
insert into common_noun_baker_translations (lemma, english_translation) values ('φόρος','tax');
insert into common_noun_baker_translations (lemma, english_translation) values ('χείρ','hand');
insert into common_noun_baker_translations (lemma, english_translation) values ('χιτών','clothing, undergarments');
insert into common_noun_baker_translations (lemma, english_translation) values ('χρόνος','time');
insert into common_noun_baker_translations (lemma, english_translation) values ('χώρα','country, countryside');
insert into common_noun_baker_translations (lemma, english_translation) values ('ψυχή','soul, life');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀγρός','field');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀδελφή','sister');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀδελφός','brother');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀκοή','rumor');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀνήρ','man, husband');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀποθήκη','barn');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀπόστολος','apostle');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀργύριον','silver, money');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀρχή','beginning');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀρχιερεύς','chief priest');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀσπασμός','greeting');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἀστήρ','star');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἁμαρτία','sin');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἄγγελος','angel');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἄνεμος','wind');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἄνθρωπος','man');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἄρτος','bread');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἄρχων','ruler');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἐντολή','commandment');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἐξουσία','authority');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἐργάτης','worker');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἔθνος','nation');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἔργον','work');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἔτος','year');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἡγεμών','governor, ruler');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἡμέρα','day');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἰχθύς','fish');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἱερεύς','priest');
insert into common_noun_baker_translations (lemma, english_translation) values ('ἱμάτιον','coat');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὀφειλέτης','debtor');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὀφθαλμός','eye');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὀψάριον','small fish');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὁδηγός','guide');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὁδός','way');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὄνομα','name');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὄρος','mountain');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὄφις','poison');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὄχλος','crowd');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὅρκος','oath');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὑδρία','water jar');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὕδωρ','water');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὥρα','hour');
insert into common_noun_baker_translations (lemma, english_translation) values ('ῥῆμα','word');
insert into common_noun_baker_translations (lemma, english_translation) values ('καθηγητής','teacher, guide');
insert into common_noun_baker_translations (lemma, english_translation) values ('κλείς','key');
insert into common_noun_baker_translations (lemma, english_translation) values ('οἶκος','house, home');
insert into common_noun_baker_translations (lemma, english_translation) values ('σύνδουλος','fellow-servant, colleague');
insert into common_noun_baker_translations (lemma, english_translation) values ('ὀδούς','tooth');
insert into common_noun_baker_translations (lemma, english_translation) values ('ῥάπισμα','slap, strike, hit');
insert into common_noun_baker_translations (lemma, english_translation) values ('λύκος','wolf');
